version: "2"

services:
  nginx:
    build:
      context: nginx
    restart: on-failure
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - hashcat

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  hashcat:
    build:
      context: .
    restart: on-failure
    depends_on:
      - postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME}
      MD5_AUTH_EMAIL: ${MD5_AUTH_EMAIL}
      MD5_AUTH_CODE: ${MD5_AUTH_CODE}
      SENDER_AUTH_USERNAME: ${SENDER_AUTH_USERNAME}
      SENDER_AUTH_PASSWORD: ${SENDER_AUTH_PASSWORD}
