spring:
  application:
    name: hashcat
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties.hibernate:
      generate_statistics: true
      session:
        events.log.LOG_QUERIES_SLOWER_THAN_MS: 1
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOSTNAME}:${POSTGRES_PORT}/${POSTGRES_DB}
    hikari:
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}

logging:
  level:
    org.hibernate.stat: DEBUG

md5:
  auth:
    email: ${MD5_AUTH_EMAIL}
    code: ${MD5_AUTH_CODE}

sender:
  auth:
    userName: ${SENDER_AUTH_USERNAME}
    password: ${SENDER_AUTH_PASSWORD}

application:
  link:
    http://localhost:8080/api/v1/verifyEmail/
